sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: memory_use_percent
      - type: processor_use
      - type: processor_temperature
x375_fan:
python_script: